name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install CMake
      run: sudo apt-get update && sudo apt-get install -y cmake
    - name: configure
      run: ./configure.sh
    - name: make
      run: cd build && make
    - name: run tests
      run: cd build && ./novasyntax_test
